on: [push]
defaults:
  shell: pwsh

jobs:
  run-on-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nikeee/setup-pandoc@v1
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install
        shell: pwsh
        run: |
          npx --yes playwright install --with-deps chromium
          sudo apt-get install -y optipng
          touch /tmp/installed