on: push
defaults:
  run:
    shell: pwsh
    working-directory: /home/runner/work/psu-themes/psu-themes/Repository/dashboards/kbupdate

jobs:
  process-json:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Execute json downloader
      run: Invoke-WebRequest -Uri  https://www.atomcorp.dev/api/v1/themes -OutFile windows-terminal-themes.json

    - name: Install
      run: |
        sudo snap install pastel
        npm install -g playwright
        npm i -D @playwright/test
        npx --yes playwright install --with-deps chromium

    - name: Run things
      run: |
        Get-ChildItem ../../../process-json.ps1 | Select-Object Name
        Get-ChildItem ./screenshots.ps1 | Select-Object Name
        
        ./screenshots.ps1
        
          