on: push
env:
  POSTGRES_DB: postgres
  POSTGRES_PASSWORD: postgres_password
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres

jobs:
  process-json:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout prism repo
      uses: actions/checkout@v3
      with:
        repository: primer/prism
        path: prism

    - name: Checkout prism api repo
      uses: actions/checkout@v3
      with:
        repository: primer/api
        path: api

    - name: Docker
      run: docker run -d postgres

    - name: Prism
      run: |
        cd prism
        yarn
        yarn start &

    - name: API
      run: |
        cd api
        npm run setup
        npm i --save-dev prisma@latest
        npm i @prisma/client@latest
        npm run dev --w api &

    - name: Sleep 20
      run: sleep 20
        
    - name: Test prism
      run: wget  http://localhost:3000

    - name: Sleep 60
      run: sleep 60

    - name: Test API
      run: wget http://localhost:4000

    - name: Execute json downloader
      run: wget -o windows-terminal-themes.json https://www.atomcorp.dev/api/v1/themes