on: push
defaults:
  run:
    shell: pwsh
    working-directory: /home/runner/work/psu-themes/psu-themes/Repository/dashboards/kbupdate

jobs:
  process-json:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Execute json downloader
      run: Invoke-WebRequest -Uri  https://www.atomcorp.dev/api/v1/themes -OutFile windows-terminal-themes.json

    - name: Install pastel
      run: sudo snap install pastel

    - name: Install
      shell: bash
      run: |
        npm install -D @playwright/test @types/faker playwright
        npm install @playwright
        npx playwright install

    - name: Run things
      run: |
        Get-ChildItem ../../../process-json.ps1 | Select-Object Name
        Get-ChildItem ./screenshots.ps1 | Select-Object Name
        
        ./screenshots.ps1
        
          