on: push
defaults:
  run:
    shell: pwsh

jobs:
  process-json:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Execute json downloader
      run: Invoke-WebRequest -Uri  https://www.atomcorp.dev/api/v1/themes -OutFile windows-terminal-themes.json

    - name: Parse and write
      run: ./process-json.ps1 # Invoke-RestMethod 'https://www.thecolorapi.com/scheme?hex=4C1AF3&mode=monochrome&count=5&format=json'
