on: push
defaults:
  run:
    shell: pwsh

jobs:
  process-json:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Prism
      run: |
        git clone git@github.com:primer/prism.git
        cd prism
        yarn
        yarn start

    - name: Execute json downloader
      run: Invoke-WebRequest -Uri  https://www.atomcorp.dev/api/v1/themes -OutFile windows-terminal-themes.json

    - name: Parse and write
      run: ./process-json.ps1