on: push
defaults:
  run:
    shell: pwsh

jobs:
  process-json:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: primer/prism
        path: prism

    - name: Prism
      shell: bash
      run: |
        cd prism
        yarn
        & yarn start
        sleep 20

    - name: Execute json downloader
      run: Invoke-WebRequest -Uri  https://www.atomcorp.dev/api/v1/themes -OutFile windows-terminal-themes.json

    - name: Parse and write
      run: ./process-json.ps1