
on: [push]

jobs:
  run-on-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Install playwright
      run: |
        npx --yes playwright install --with-deps chromium
        npm install -D @playwright/test
        npm install playwright

    - name: Execute json downloader
      run: |
        node ./tests/download-json.js

    - name: Do it
      shell: pwsh
      run: |
        $themes = Get-Content windows-terminal-themes.json | ConvertFrom-Json
        foreach ($theme in $themes) {
          $isdark = Test-DarkColor $theme.background
          [pscustomobject]@{
            Name = $theme.Name
            Theme = switch ($isdark) {
              $false  { "Light" }
              $true   { "Dark" }
            }
          }
        }