on: push
defaults:
  run:
    shell: pwsh

jobs:
  run-on-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Execute json downloader
      run: Invoke-WebRequest -Uri  https://www.atomcorp.dev/api/v1/themes -OutFile windows-terminal-themes.json

    - name: Do it
      shell: pwsh
      run: |
        $themes = Get-Content windows-terminal-themes.json | ConvertFrom-Json
        . ./Repository/dashboards/kbupdate/private/functions.ps1
        foreach ($theme in $themes) {
          $isdark = Test-DarkColor $theme.background
          [pscustomobject]@{
            Name = $theme.Name
            Theme = switch ($isdark) {
              $false  { "Light" }
              $true   { "Dark" }
            }
          }
        }