
on: [push]

jobs:
  run-on-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: potatoqualitee/ogimage@v1.0

      - name: Execute json downloader
        shell: bash
        run: |
          npm install -g playwright
          node ./tests/download-json.js
          ls