name: JSON Converter
on: 
  workflow_dispatch:
defaults:
  run:
    shell: pwsh

jobs:
  create-screenshots:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Execute json downloader
      run: Invoke-WebRequest -Uri  https://www.atomcorp.dev/api/v1/themes -OutFile ./tools/windows-terminal-themes.json

    - name: Install pastel
      run: sudo snap install pastel

    - name: Update theme files
      run: |
        ./tools/wintheme-to-psu.ps1
      
    - name: 🪠 Upload db to artifact
      uses: actions/upload-artifact@v3
      with:
        name: theme-files
        path: "/home/runner/work/psu-themes/psu-themes/Repository/dashboards/psu-themes/themes"
        
          
